### ISSUE TITLE
Add parameter server

### ISSUE THREAD

**Issue by bjsowa** [LeoRover/leocore_firmware_ros2#2]
The firmware should implement parameter declaring and handling. The [rclc_parameter](https://index.ros.org/p/rclc_parameter/github-ros2-rclc/) package is not available in Foxy distribution for now. Unless the maintainers decide to backport this package (ros2/rclc#262), it will need to be somehow included in [microros_lib](https://github.com/fictionlab/microros_lib).

**Comment by pablogs9** [comment]
Take a look here: https://github.com/ros2/rclc/pull/263#event-6248973394
