### ISSUE TITLE
Available or not : ros2 firmware .bin file 

### ISSUE THREAD

**Issue by Jaynkd** [LeoRover/leocore_firmware_ros2#3]
Hi, 

May I have a link or the .bin file for the ros2_based experimental firmware. Currently the build is failing in PlatformIO.

![Screenshot from 2022-08-02 11-47-59](https://user-images.githubusercontent.com/110478948/182417554-66ccfb11-b87d-48a2-abc8-79ae86ff63d1.png)

**Comment by bjsowa** [comment]
Hi, the project should now build successfully. Could you pull the newest changes and try again ? I will upload the `.bin` file once I'll  publish the first release.

**Comment by bjsowa** [comment]
We just published the first release, you can download the compiled binary on the releases page:
https://github.com/LeoRover/leocore_firmware_ros2/releases
